### PR TITLE
Fix for Laravel 5.5

### PR DESCRIPTION
**Pull request by Braunson**
PR #5 

https://laravel.com/docs/5.5/upgrade#artisan

### CODE REVIEW

**Comment by tremby** [comment]
Is this backwards-compatible?

Have you tried Laravel Horizon, mentioned in #5?

**Comment by Braunson** [comment]
Yes I've used Laravel Horizon, the PR was for anyone who wants to continue to use your package in 5.5.

I've updated the PR to make it backwards-compatible.

**Comment by tremby** [comment]
Thanks. Last thing: can you add a small sentence to each of those docstrings to say which Laravel versions they're for?

And then squash your commits (or I can) and I'll merge.

**Comment by tremby** [comment]
Can you comment on whether Laravel Horizon is a good replacement for this? I'll add a note to the readme if so.

**Comment by Braunson** [comment]
Sure I'll add the comments now..

@tremby Laravel Horizon is a decent replacement the only caveat is Horizon requires PHP 7.1+ due to its usage of async process signals, 

So users running 7.0 -> 7.1 won't be able to use Horizon, which is where your packages comes into use 😄

**Comment by tremby** [comment]
Thanks for that.

**Comment by tremby** [comment]
I squashed and merged this. Thanks! I tagged v2.3.4.

**Pull request closed without merging**
